import Head from 'next/head'
import React from 'react'


export default function Home() {
  return (
    <div>
      <Head>
        <title>HomePage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello Next.js</h1>
      </main>
    </div>
  )
}
